import "./globals.css";
export const metadata = {
  title: "Todo App",
  description: "Generated by Todo List app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
